### ISSUE TITLE
Run API tests as part of the pipeline

### ISSUE THREAD

**Issue by helicalbytes** [DoESLiverpool/optimism#62] opened 2022-03-24 22:26 UTC
The tests themselves live in the api folder. So they can be copied into a container via a Dockerfile if required. They should also run outside of a container.

They should be required to pass before merging to develop or master branches.

**Comment by amcewen** [comment] 2022-05-03 19:19
This is a duplicate of #32

**Closed by amcewen** 2022-05-03 19:19 UTC
Labels: duplicate
